---
- name: Recipe for how to build deploy image
  hosts: localhost

  vars:
    local_home: "{{ lookup('env','HOME') }}"

  tasks:
  - name: Get zsh
    get_url:
      url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
      dest: "{{ local_home }}/install.sh"

  - name: Check if Oh-my-zsh exists
    stat: path={{ local_home }}/.oh-my-zsh
    register: ohmyzsh

  - name: Install Oh-my-zsh
    command: bash {{ local_home }}/install.sh
    when: not ohmyzsh.stat.isdir 

  - name: Install ansible-bender headers
    pip:
      name: git+https://github.com/ansible-community/ansible-bender
      executable: pip3
