---
- name: Recipe for how to build deploy image
  hosts: localhost

  tasks:
  - name: Install all packages needed for Fedora workstation.
    dnf:
      name:
      - ansible
      - origin-clients
      - podman
      - buildah
      - zsh
      - gcc
      - make
      - git
      - python-devel
      - terminator  
      - python3-pip
      - kernel-headers
      - kernel-devel
      - gnome-tweak-tool
      - autoconf
      - dkms
      state: present
  - name: Get kernel version from Fedora Linux Workstation
    command: uname -r
    register: uname

  - name: Install kernel headers for Virtual Box Guest additions
    dnf:
      name:
      - kernel-devel-{{ uname.stdout }}
      state: present
